# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 333fc3dbb7630e5d012a0b471d03672af68d2e12622ece0eaf29a9aab04fada55b88ab6f1a0baade613d36c22043b9239aba344faa960ceae252b93fb4c3bee2

test:
  secret_key_base: 99d79ea545bbe90be6ec466f7eea75181cd36331d01b02b02536e898c1ab46c678fbeb87a7bd6739ed60e714284b59793a56f2029c2380eae3e90b42986a0adb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
